'use strict';var math={};var random={};var time={};import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,
__in__,__init__,__ior__,__ipow__,__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,abs,all,any,assert,bool,bytearray,bytes,callable,chr,copy,deepcopy,delattr,dict,dir,divmod,
enumerate,filter,float,getattr,hasattr,input,int,isinstance,issubclass,len,list,map,max,min,object,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";import*as __module_time__ from"./time.js";__nest__(time,"",__module_time__);import*as __module_random__ from"./random.js";__nest__(random,"",__module_random__);import*as __module_math__ from"./math.js";__nest__(math,"",__module_math__);
var __name__="__main__";var counter=0;var queue={};var channel=new MessageChannel;channel.port1.onmessage=function(event){var id=event.data;var callback=queue[id];delete queue[id];callback()};const setImmediate=(callback)=>{queue[++counter]=callback;channel.port2.postMessage(counter)};function scheduleCallback(callback,timeout){if(timeout<4)setImmediate(callback);else setTimeout(callback,timeout)}function sleep(aTime,asio){return new Promise((resolve)=>{scheduleCallback(()=>{resolve(aTime)},1E3*aTime)})}
export var display=function(s){document.getElementById("output").innerHTML+=s+"<br />"};export var bench_input_size=1E5;export var bench_min_duration=.2;export var bench_best_of=1;export var default_timer=time.time;export var default_time_diff=function __lambda__(a,b){return a-b};export var l=null;export var timeit=function(func,iterations,timer,time_diff,args){if(typeof iterations=="undefined"||iterations!=null&&iterations.hasOwnProperty("__kwargtrans__"))var iterations=bench_input_size;if(typeof timer==
"undefined"||timer!=null&&timer.hasOwnProperty("__kwargtrans__"))var timer=default_timer;if(typeof time_diff=="undefined"||time_diff!=null&&time_diff.hasOwnProperty("__kwargtrans__"))var time_diff=default_time_diff;if(typeof args=="undefined"||args!=null&&args.hasOwnProperty("__kwargtrans__"))var args=[];var t1=timer();var res=func();for(var _=0;_<iterations-1;_++)func();var timing=time_diff(timer(),t1);return tuple([timing,res])};export var timeit_async=async function(func,iterations,timer,time_diff,
args){if(typeof iterations=="undefined"||iterations!=null&&iterations.hasOwnProperty("__kwargtrans__"))var iterations=bench_input_size;if(typeof timer=="undefined"||timer!=null&&timer.hasOwnProperty("__kwargtrans__"))var timer=default_timer;if(typeof time_diff=="undefined"||time_diff!=null&&time_diff.hasOwnProperty("__kwargtrans__"))var time_diff=default_time_diff;if(typeof args=="undefined"||args!=null&&args.hasOwnProperty("__kwargtrans__"))var args=[];var t1=timer();var res=await func();for(var _=
0;_<iterations-1;_++)await func();var timing=time_diff(timer(),t1);return tuple([timing,res])};export var autorange=function(func,args){if(typeof args=="undefined"||args!=null&&args.hasOwnProperty("__kwargtrans__"))var args=[];var i=1;while(true){for(var j of tuple([1,2,5])){var iterations=i*j;var __left0__=timeit(func,iterations,__kwargtrans__({args:args}));var time_taken=__left0__[0];var res=__left0__[1];if(time_taken>=bench_min_duration)return tuple([time_taken/iterations,res])}i*=10}};export var autorange_async=
async function(func){var args=tuple([].slice.apply(arguments).slice(1));var i=1;while(true){for(var j of tuple([1,2,5])){var iterations=i*j;var __left0__=await timeit_async(func,iterations,__kwargtrans__({args:args}));var time_taken=__left0__[0];var res=__left0__[1];if(time_taken>=bench_min_duration)return tuple([time_taken/iterations,res])}i*=10}};export var bench=function(py_name){var _bench=function(func){var wrapper=function(){var args=tuple([].slice.apply(arguments).slice(0));var min_time_taken=
float("inf");var res=null;for(var _=0;_<bench_best_of;_++){var __left0__=autorange(func,__kwargtrans__({args:args}));var time_taken=__left0__[0];var res=__left0__[1];var min_time_taken=min(min_time_taken,time_taken)}print_bench(py_name,min_time_taken,__kwargtrans__({args:args}));return res};return wrapper};return _bench};export var bench_async=function(py_name){var _bench=function(func){var wrapper=async function(){var args=tuple([].slice.apply(arguments).slice(0));var min_time_taken=float("inf");
var res=null;for(var _=0;_<bench_best_of;_++){var __left0__=await autorange_async(func);var time_taken=__left0__[0];var res=__left0__[1];var min_time_taken=min(min_time_taken,time_taken)}print_bench(py_name,min_time_taken,...args);return res};return wrapper};return _bench};export var format_ms=function(ops){var ms=1E3/ops;return"{} ms".format(ops)};export var _repr=function(arg){try{var l=len(arg);if(l>10)return"{}[{}]".format(py_typeof(arg).__name__,l);return repr(arg)}catch(__except0__){return repr(arg)}};
export var format_args=function(){var args=tuple([].slice.apply(arguments).slice(0));var args_repr=function(){var __accu0__=[];for(var arg of args)__accu0__.append(_repr(arg));return __accu0__}();var args_fmt=", ".join(args_repr);if(args_fmt!="")var args_fmt="({})".format(args_fmt);return args_fmt};export var metric=function(value,unit,precision){if(typeof unit=="undefined"||unit!=null&&unit.hasOwnProperty("__kwargtrans__"))var unit="";if(typeof precision=="undefined"||precision!=null&&precision.hasOwnProperty("__kwargtrans__"))var precision=
3;if(!math.isfinite(value))return _format_not_finite(value);var exponent=value!=0?int(math.floor(math.log10(abs(value)))):0;value/=Math.pow(10,Math.floor(exponent/3)*3);if(exponent>=3)var ordinal_="kMGTPEZYRQ"[Math.floor(exponent/3)-1];else if(exponent<0)var ordinal_="m\u03bcnpfazyrq"[Math.floor((-exponent-1)/3)];else var ordinal_="";var precision=max(0,precision-__mod__(exponent,3)-1);var value=round(value,precision);var value_=format(value,__mod__(".%if",precision));if(!(unit||ordinal_)||__in__(unit,
tuple(["\u00b0","\u2032","\u2033"])))var space="";else var space=" ";return"{}{}{}{}".format(value_,space,ordinal_,unit)};export var f=function(x,unit){if(typeof unit=="undefined"||unit!=null&&unit.hasOwnProperty("__kwargtrans__"))var unit="ns";var x=round(x,1);return"{} {}".format(x,unit)};export var format_num=function(ops,unit){if(typeof unit=="undefined"||unit!=null&&unit.hasOwnProperty("__kwargtrans__"))var unit="";if(ops<10)var ops=round(ops,2);else var ops=round(ops);var __left0__="{}".format(ops).py_split(".");
var int_part=__left0__[0];var float_part=__left0__[1];var res="";var i=0;for(var c of py_reversed(list(int_part))){if(__mod__(i,3)==0&&i>0)res+=",";res+=c;i++}if(float_part)return"{}.{} {}".format(res,float_part,unit);return"{} {}".format("".join(py_reversed(list(res))),unit)};export var align_left=function(value,tabsize){if(typeof tabsize=="undefined"||tabsize!=null&&tabsize.hasOwnProperty("__kwargtrans__"))var tabsize=25;var spaces="";for(var _=0;_<max(0,tabsize-len(value));_++)spaces+=" ";if(spaces!=
"")return"{}{}".format(value,spaces);return value};export var align_right=function(value,tabsize){if(typeof tabsize=="undefined"||tabsize!=null&&tabsize.hasOwnProperty("__kwargtrans__"))var tabsize=25;var spaces="";for(var _=0;_<max(0,tabsize-len(value));_++)spaces+=" ";if(spaces!="")return"{}{}".format(spaces,value);return value};export var print_bench=function(label,time,tabsize,args){if(typeof tabsize=="undefined"||tabsize!=null&&tabsize.hasOwnProperty("__kwargtrans__"))var tabsize=25;if(typeof args==
"undefined"||args!=null&&args.hasOwnProperty("__kwargtrans__"))var args=[];var label="{}{}:".format(label,format_args(...args));var label=align_left(label);var ms_str=align_right("{}".format(format_num(1E3*time,"ms")),10);var ops_str=align_right("{}".format(format_num(1/time,"ops/s")),tabsize);display("{}\t{}\t{}".format(label,ms_str,ops_str))};export var assign=bench("assign")(function(iters){if(typeof iters=="undefined"||iters!=null&&iters.hasOwnProperty("__kwargtrans__"))var iters=bench_input_size;
for(var _=0;_<iters;_++)var x=1});export var multiply=bench("multiply")(function(iters){if(typeof iters=="undefined"||iters!=null&&iters.hasOwnProperty("__kwargtrans__"))var iters=bench_input_size;for(var _=0;_<iters;_++)17*47});export var bigint_add=bench("bigint_add")(function(iters){if(typeof iters=="undefined"||iters!=null&&iters.hasOwnProperty("__kwargtrans__"))var iters=bench_input_size;var x=1;for(var _=0;_<iters;_++)x+=Math.pow(2,600);return x});export var bigint_mult=bench("bigint_mult")(function(iters){if(typeof iters==
"undefined"||iters!=null&&iters.hasOwnProperty("__kwargtrans__"))var iters=bench_input_size;var x=1;for(var _=0;_<iters;_++)x*=Math.pow(2,600);return x});export var randlist=bench("randlist")(function(size){if(typeof size=="undefined"||size!=null&&size.hasOwnProperty("__kwargtrans__"))var size=bench_input_size;return function(){var __accu0__=[];for(var _=0;_<size;_++)__accu0__.append(random.randint(0,size));return __accu0__}()});export var _randlist=function(size){if(typeof size=="undefined"||size!=
null&&size.hasOwnProperty("__kwargtrans__"))var size=bench_input_size;return function(){var __accu0__=[];for(var _=0;_<size;_++)__accu0__.append(random.randint(0,size));return __accu0__}()};var l=_randlist();export var cpylist=bench("cpylist")(function(){return l.__getslice__(0,null,1)});export var sortlist=bench("sortlist")(function(){return sorted(l.__getslice__(0,null,1))});export var sortlist2=bench("sortlist2")(function(){return l.__getslice__(0,null,1).py_sort()});export var fibonacci=bench("fibonacci")(function(n){if(typeof n==
"undefined"||n!=null&&n.hasOwnProperty("__kwargtrans__"))var n=bench_input_size;if(n<2)return n;var __left0__=tuple([1,2]);var a=__left0__[0];var b=__left0__[1];for(var _=0;_<n-1;_++){var __left0__=tuple([b,__mod__(a+b,1E5)]);var a=__left0__[0];var b=__left0__[1]}return a});export var primes=bench("primes")(function(n){if(typeof n=="undefined"||n!=null&&n.hasOwnProperty("__kwargtrans__"))var n=bench_input_size;if(n==2)return[2];if(n<2)return[];var s=list(range(3,n+1,2));var mroot=Math.pow(n,.5);var half=
Math.floor((n+1)/2)-1;var i=0;var m=3;while(m<=mroot){if(s[i]){var j=Math.floor((m*m-3)/2);s[j]=0;while(j<half){s[j]=0;j+=m}}var i=i+1;var m=2*i+3}return[2]+function(){var __accu0__=[];for(var x of s)if(x)__accu0__.append(x);return __accu0__}()});export var tryexcept=bench("tryexcept")(function(){for(var _=0;_<bench_input_size;_++)try{var __except0__=Exception("test");__except0__.__cause__=null;throw __except0__;}catch(__except0__){if(isinstance(__except0__,Exception))var exc=__except0__;else throw __except0__;
}});export var fn=function(){};export var callfunc=bench("callfunc")(function(){for(var _=0;_<bench_input_size;_++)fn()});export var ret=bench("ret")(function(){return true});export var async_nothing=bench_async("async_nothing")(async function(){});export var async_sleep_0=bench_async("async_sleep_0")(async function(){await sleep(0)});export var nothing=bench("nothing")(function(){for(var _=0;_<bench_input_size;_++);});export var CancelledException=__class__("CancelledException",[Exception],{__module__:__name__});
export var set_best_of=function(best_of){bench_best_of=best_of};export var set_min_duration=function(min_duration){bench_min_duration=min_duration};export var Bench=__class__("Bench",[object],{__module__:__name__,cancelled:false,get cancel(){return __get__(this,function(self){self.cancelled=true})},get _run(){return __get__(this,async function(self,fn){if(self.cancelled){var __except0__=CancelledException;__except0__.__cause__=null;throw __except0__;}fn();await sleep(.1)})},get run(){return __get__(this,
async function(self){try{await self._run(randlist);await self._run(nothing);await self._run(callfunc);await self._run(bigint_add);await self._run(bigint_mult);await self._run(cpylist);await self._run(sortlist);await self._run(sortlist2);await self._run(fibonacci);await self._run(primes);await self._run(tryexcept)}catch(__except0__){if(isinstance(__except0__,Exception)){var e=__except0__;console.warn("exception",e)}else console.warn("unknown exception")}})}});

//# sourceMappingURL=bench.map